### PR TITLE
Add Motors page

### PR DESCRIPTION
**Pull request by bennuttall**
@MarcScott I've written a page on learning how to use motors, starting with `OutputDevice`, then `Motor`, then `Robot`. I think the content is complete, it just needs some diagrams.

I'll get it copy edited and then you can merge it when you're happy.

### CODE REVIEW

**Comment by bennuttall** [comment]
Just remembered I didn't finish the intro. Could do with some help explaining an h-bridge, and maybe the stuff I wrote about 5V with motors was wrong. @MarcScott @jrobinson-uk

**Comment by LornaLynch** [comment]
Just a note: I removed the reference to "Explain H Bridge" while copy editing. Just in case it got pushed through like that for some reason...

**Comment by lurch** [comment]
A lot of motor tutorials I've seen use 6V to run the motors, i.e. 4xAA batteries. Not sure what you meant by "variable supply"? The main factor is that motors are high-current devices, and typically need much more current than the Pi itself is able to supply.

https://en.wikipedia.org/wiki/H_bridge

**Comment by MarcScott** [comment]
I'll do a full explanation of H bridges and fly-back diodes once the graphics are done and this is ready to be merged.

**Comment by bennuttall** [comment]
Not got around to this so if you get chance, Marc, do it! Would be good to have this merged soon.

**Comment by bennuttall** [comment]
@MarcScott I added the missing images. Ideally they'll be replaced with Sam versions but I think it's good to go live now. It's been copy edited. Ok to merge?

**Comment by MarcScott** [comment]
Sorry - saw this late. I assume you've done this now.
Ben Nuttall writes:

> @MarcScott I added the missing images. Ideally they'll be replaced with Sam versions but I think it's good to go
> live now. It's been copy edited. Ok to merge?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Marc Scott

Content & Curriculum Manager
Raspberry Pi Foundation

**Pull request merged**
