### PR TITLE
Add analogue worksheet

### PR DESCRIPTION
**Pull request by bennuttall**
I've added a worksheet which teaches analogue inputs using the MCP3008 on a breadboard.

@LornaLynch @lauraclay can you please copy edit analogue.md in the analogue branch?

@MarcScott I've added all images (fritzing) - these will do until @samalderhyde can do them.

### CODE REVIEW

**Comment by LornaLynch** [comment]
Copy edit is done now, @bennuttall. Let me know if there are any problems.

**Comment by bennuttall** [comment]
@MarcScott you can merge if you're happy.

If you're happy and you know it, merge.

**Comment by bennuttall** [comment]
@lurch did you say you spotted an error?

**Comment by MarcScott** [comment]
@bennuttall can you raise an issue for the graphics please.

**Comment by lurch** [comment]
> @lurch did you say you spotted an error?

Yeah, but it was fixed by 946c262b763f27f4f7bb86c429a670abca3d081f ;-)  Well done @LornaLynch

**Comment by bennuttall** [comment]
@MarcScott I have the diagrams from @samalderhyde. Will upload today.

**Comment by MarcScott** [comment]
Okay, will pull once uploaded and checked
Ben Nuttall writes:

> @MarcScott I have the diagrams from @samalderhyde. Will upload today.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Marc Scott

Content & Curriculum Manager
Raspberry Pi Foundation

**Comment by bennuttall** [comment]
Done

**Pull request merged**
